{{- if .Values.roleBinding.create -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "secret-sync.roleBindingName" . }}
  labels:
    {{- include "secret-sync.labels" . | nindent 4 }}
  {{- with .Values.roleBinding.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
- kind: ServiceAccount
  name: {{ include "secret-sync.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "secret-sync.roleName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
