{{- if .Values.role.create -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "secret-sync.roleName" . }}
  labels:
    {{- include "secret-sync.labels" . | nindent 4 }}
  {{- with .Values.role.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get","create","patch", "list", "delete"]
{{- end }}
