replicaCount: 1

image:
  repository: csepulveda/secret-sync
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: "secret-sync"

role:
  create: true
  annotations: {}
  name: "secret-sync"

roleBinding:
  create: true
  annotations: {}
  name: "secret-sync"

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources: {}

env:
  "INTERVAL": "120"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
